// Whitelist of GuildSettings fields the dashboard is allowed to PATCH.
// Keeping this explicit (rather than accepting any body key) stops a crafted
// request from writing to fields the UI never exposes.
export const EDITABLE_SETTINGS_FIELDS = [
  'moderationEnabled',
  'antiScamEnabled',
  'musicEnabled',
  'ticketsEnabled',
  'modmailEnabled',
  'levelingEnabled',
  'economyEnabled',
  'voiceHubEnabled',
  'giveawaysEnabled',
  'reactionRolesEnabled',
  'socialAlertsEnabled',
  'aiEnabled',
  'prefix',
  'logChannelId',
  'staffRoleIds',
  'adminRoleIds',
  'automodBlockInvites',
  'automodBlockBadWords',
  'automodBadWords',
  'automodBlockSpam',
  'automodSpamMsgCount',
  'automodSpamWindowSec',
  'automodBlockGhostPing',
  'automodWhitelistRoleIds',
  'automodWhitelistChannelIds',
  'modLogChannelId',
  'warningDecayDays',
  'antiScamAction',
  'antiScamTimeoutMin',
  'antiScamWhitelistRoleIds',
  'antiScamWhitelistChannelIds',
  'aiChatChannelIds',
  'aiMode',
  'aiPersonality',
  'aiEscalationChannelId',
  'aiConfidenceThreshold',
  'xpPerMessage',
  'xpCooldownSec',
  'xpPerVoiceMin',
  'xpLevelUpBase',
  'levelUpChannelId',
  'levelRoleRewards',
  'economyCurrencyName',
  'economyCurrencySymbol',
  'economyDailyAmount',
  'economyWorkMin',
  'economyWorkMax',
  'economyRobEnabled',
  'economyRobSuccessRate',
  'ticketLogChannelId',
  'ticketMaxOpenPerUser',
  'ticketReminderHours',
  'ticketBlockedRoleIds',
  'ticketOverflowCategoryIds',
  'modmailCategoryId',
  'modmailLogChannelId',
  'voiceHubSetupChannelId',
  'voiceHubCategoryId',
  'voiceHubDefaultName',
  'voiceHubDefaultLimit',
  'welcomeEnabled',
  'welcomeChannelId',
  'welcomeMessage',
  'leaveEnabled',
  'leaveChannelId',
  'leaveMessage',
  'autoRoleIds',
  'musicMaxQueue',
  'musicDefaultVol',
  'musicDjRoleIds'
] as const;

export type EditableSettingsField = (typeof EDITABLE_SETTINGS_FIELDS)[number];
