package com.angkor.makongcore.command;
import com.angkor.makongcore.MakongCore;
import com.angkor.makongcore.service.MaTierService;
import com.angkor.makongcore.data.Database;
import com.angkor.makongcore.util.Text;
import org.bukkit.Bukkit;import org.bukkit.OfflinePlayer;import org.bukkit.command.*;import org.bukkit.entity.Player;
import java.util.*;
public final class MaTierCommand implements CommandExecutor,TabCompleter{
 private final MakongCore plugin;private final MaTierService s;public MaTierCommand(MakongCore p,MaTierService s){plugin=p;this.s=s;}
 public boolean onCommand(CommandSender sender,Command cmd,String label,String[] a){if(a.length==0)return profile(sender,sender instanceof Player?(Player)sender:null);String sub=a[0].toLowerCase(Locale.ROOT);if(sub.equals("top"))return top(sender);if(!sender.hasPermission("makongcore.admin")){sender.sendMessage(Text.mm(s.msg("matier.messages.admin_only")));return true;}if(sub.equals("reload")){plugin.reloadMakongCore(sender);return true;}if(a.length<2){help(sender);return true;}OfflinePlayer p=Bukkit.getOfflinePlayer(a[1]);if(!p.hasPlayedBefore()&&!p.isOnline()){sender.sendMessage(Text.mm(s.msg("matier.messages.no_player")));return true;}String pname=p.getName()!=null?p.getName():a[1];switch(sub){case "stats"->profile(sender,p);case "set","add","remove"->{if(a.length<3){help(sender);return true;}try{long n=Long.parseLong(a[2]);if(sub.equals("set"))s.setStars(p.getUniqueId(),pname,n);else s.addStars(p.getUniqueId(),pname,sub.equals("add")?n:-n,false);sender.sendMessage(Text.mm("<green>done.</green> <gray>"+pname+" now has <yellow>"+s.stars(p.getUniqueId())+"★</yellow>.</gray>"));}catch(NumberFormatException e){sender.sendMessage(Text.mm(s.msg("matier.messages.invalid_amount")));}}case "reset"->s.setStars(p.getUniqueId(),pname,0);case "resetall"->{for(Database.PlayerStar x:s.sorted())s.setStars(x.uuid(),x.name(),0);sender.sendMessage(Text.mm("<green>all matier stars reset.</green>"));}default->help(sender);}return true;}
 private boolean profile(CommandSender sender,OfflinePlayer p){if(p==null){sender.sendMessage(Text.mm("<red>players only.</red>"));return true;}String pname=p.getName()!=null?p.getName():"Unknown";long st=s.stars(p.getUniqueId());String tier=s.tier(p.getUniqueId());String next="MAX";long req=st;if(!tier.equals("M1")){String[] ts={"M9","M8","M7","M6","M5","M4","M3","M2","M1"};for(String t:ts){long r=s.config().getLong("matier.tiers."+t);if(r>st){next=t;req=r;break;}}}String nextDisplay=next.equals("MAX")?"<gold>MAX</gold>":MaTierService.coloredTier(next);sender.sendMessage(Text.mm(s.msg("matier.messages.profile").replace("{player}",pname).replace("{tier}",MaTierService.coloredTier(tier)).replace("{stars}",String.valueOf(st)).replace("{next_tier}",nextDisplay).replace("{required}",String.valueOf(req))));return true;}
 private boolean top(CommandSender sender){sender.sendMessage(Text.mm(s.msg("matier.messages.top_header")));int max=s.config().getInt("matier.leaderboard.size",10);int i=0;for(Database.PlayerStar p:s.sorted()){if(++i>max)break;sender.sendMessage(Text.mm(s.msg("matier.messages.top_entry").replace("{rank}",String.valueOf(i)).replace("{tier}",MaTierService.coloredTier(s.tier(p.uuid()))).replace("{player}",p.name()).replace("{stars}",String.valueOf(p.stars()))));}return true;}
 private void help(CommandSender s){s.sendMessage(Text.mm("<yellow>/matier</yellow> <gray>- profile\n<yellow>/matier top</yellow> <gray>- leaderboard\n<yellow>/matier stats <player></yellow>\n<yellow>/matier set|add|remove <player> <stars></yellow>\n<yellow>/matier reset <player></yellow>\n<yellow>/matier resetall</yellow>\n<yellow>/matier reload</yellow>"));}
 public List<String> onTabComplete(CommandSender sender,Command cmd,String a,String[] args){if(args.length==1)return Arrays.asList("top","stats","set","add","remove","reset","resetall","reload").stream().filter(x->x.startsWith(args[0].toLowerCase())).toList();if(args.length==2&&Set.of("stats","set","add","remove","reset").contains(args[0].toLowerCase()))return Bukkit.getOnlinePlayers().stream().map(Player::getName).filter(x->x.toLowerCase().startsWith(args[1].toLowerCase())).toList();return List.of();}
}
