package com.angkor.makongcore.command;
import com.angkor.makongcore.MakongCore; import com.angkor.makongcore.gui.GuiManager; import com.angkor.makongcore.listener.ChatListener; import com.angkor.makongcore.model.*; import com.angkor.makongcore.service.TeamService; import com.angkor.makongcore.util.Text; import org.bukkit.*; import org.bukkit.command.*; import org.bukkit.entity.Player; import java.util.*;
public final class TeamCommand implements CommandExecutor,TabCompleter{
 private final MakongCore plugin;private final TeamService ts;private final GuiManager gui;public TeamCommand(MakongCore p,TeamService t,GuiManager g){plugin=p;ts=t;gui=g;}
 private void msg(CommandSender s,String k,Map<String,String> p){String x=plugin.teamConfig().get().getString("messages."+k,null);if(x==null){var f=plugin.getResource("messages.yml");} /* messages are intentionally simple; main prefix below */ s.sendMessage(Text.mm("<green>[ᴛᴇᴀᴍs]</green> "+switch(k){case "not_in_team"->"<red>You are not in a team.</red>";case "already_in_team"->"<red>You are already in a team.</red>";case "team_created"->"<green>Team created!</green>";case "team_not_found"->"<red>Team not found.</red>";case "not_owner"->"<red>Only the owner can do that.</red>";case "member_not_found"->"<red>Member not found.</red>";case "player_not_found"->"<red>Player not found.</red>";default->"<gray>Done.</gray>";}));}
 @Override public boolean onCommand(CommandSender s,Command c,String label,String[] a){if(!(s instanceof Player p)){s.sendMessage(Text.mm("<red>Players only.</red>"));return true;}if(!ts.settings().enabled()){s.sendMessage(Text.mm("<red>Teams are disabled on this server.</red>"));return true;}if(a.length==0){gui.open(p);return true;}String sub=a[0].toLowerCase(Locale.ROOT);if(sub.equals("browse")){gui.openBrowse(p,1);return true;}if(sub.equals("top")||sub.equals("leaderboard")){gui.openLeaderboard(p,1,"stars");return true;}if(sub.equals("help")){p.sendMessage(Text.mm("<green>/team</green> <gray>menu\n<green>/team create <tag> <name>\n/team invite <player>\n/team join <tag>\n/team kick <player>\n/team promote <player>\n/team transfer <player>\n/team ally <tag>\n/team info <tag>\n/team chat"));return true;}Team t=ts.byPlayer(p.getUniqueId());switch(sub){case "create" -> create(p,a);case "info" -> info(p,a);case "join" -> join(p,a);case "invite" -> invite(p,a,t);case "kick" -> kick(p,a,t);case "promote" -> promote(p,a,t);case "transfer" -> transfer(p,a,t);case "disband","delete" -> disband(p,t);case "chat" -> chatToggle(p,t);case "ally" -> ally(p,a,t);default -> gui.open(p);}return true;}
 private void create(Player p,String[] a){if(ts.byPlayer(p.getUniqueId())!=null){msg(p,"already_in_team",Map.of());return;}if(a.length<2){com.angkor.makongcore.listener.ChatListener.beginCreate(p);return;}
if(a.length<3){p.sendMessage(Text.mm("<yellow>Enter tag and name: <white>/team create <tag> <name></white>"));return;}String tag=a[1],name=String.join(" ",Arrays.copyOfRange(a,2,a.length));if(!tag.matches("[A-Za-z0-9_]+")){p.sendMessage(Text.mm("<red>Tag rejected: <white>only A-Z, a-z, 0-9 and _ are allowed.</white></red>"));return;}
if(tag.length()<ts.settings().minTag()||tag.length()>ts.settings().maxTag()){p.sendMessage(Text.mm("<red>Tag rejected: <white>must be "+ts.settings().minTag()+"-"+ts.settings().maxTag()+" characters.</white></red>"));return;}
if(name.length()<ts.settings().minName()){p.sendMessage(Text.mm("<red>Name rejected: <white>too short; minimum is "+ts.settings().minName()+" characters.</white></red>"));return;}
if(name.length()>ts.settings().maxName()){p.sendMessage(Text.mm("<red>Name rejected: <white>too long; maximum is "+ts.settings().maxName()+" characters.</white></red>"));return;}
if(ts.byTag(tag)!=null){p.sendMessage(Text.mm("<red>Tag rejected: <white>that tag is already in use.</white></red>"));return;}
if(ts.all().stream().anyMatch(x->x.name().equalsIgnoreCase(name))){p.sendMessage(Text.mm("<red>Name rejected: <white>that team name is already in use.</white></red>"));return;}Team t=ts.create(p.getUniqueId(),tag,name,"aqua");if(t==null){p.sendMessage(Text.mm("<red>team could not be created. <white>the tag/name may already exist or the database save failed.</white></red>"));return;}p.sendTitle("team created","<gray>"+name+"</gray>",10,50,10);p.sendMessage(Text.mm("<green>team <white>"+name+"</white> created!</green>"));plugin.gui().openColor(p,t);}
 private void info(Player p,String[] a){Team t=a.length>1?ts.byTag(a[1]):ts.byPlayer(p.getUniqueId());if(t==null){msg(p,"team_not_found",Map.of());return;}p.sendMessage(Text.mm("<aqua>"+t.name()+" <gray>["+t.tag()+"]\n<gray>Members: <white>"+t.members().size()+"/"+ts.settings().maxSize()+"\n<gray>Weekly Points: <white>"+t.points()+"\n<gray>Kills: <white>"+t.kills()+"\n<gray>Deaths: <white>"+t.deaths()+"\n<gray>KDR: <white>"+(t.deaths()==0?t.kills():String.format(Locale.US,"%.2f",(double)t.kills()/t.deaths()))+"\n<gray>Description: <white>"+t.description()));}
 private void join(Player p,String[] a){if(a.length<2)return;if(ts.byPlayer(p.getUniqueId())!=null){msg(p,"already_in_team",Map.of());return;}Team t=ts.byTag(a[1]);if(t==null){msg(p,"team_not_found",Map.of());return;}var inv=ts.invite(p.getUniqueId());if(inv!=null&&inv.team().equals(t.id())){if(ts.addMember(t,p.getUniqueId(),p.getName(),TeamRole.MEMBER)){ts.clearInvite(p.getUniqueId());p.sendMessage(Text.mm("<green>Joined <white>"+t.name()+"</white>.</green>"));}else msg(p,"team_full",Map.of());return;}if(!t.isPublic()){p.sendMessage(Text.mm("<red>That team is private.</red>"));return;}ts.request(p.getUniqueId(),t.id());p.sendMessage(Text.mm("<green>Join request sent.</green>"));}
 private void invite(Player p,String[] a,Team t){if(t==null){msg(p,"not_in_team",Map.of());return;}TeamMember me=t.member(p.getUniqueId());if(me.role()==TeamRole.MEMBER){msg(p,"not_admin",Map.of());return;}if(a.length<2)return;Player target=Bukkit.getPlayerExact(a[1]);if(target==null){msg(p,"player_not_found",Map.of());return;}if(ts.byPlayer(target.getUniqueId())!=null){p.sendMessage(Text.mm("<red>That player is already in a team.</red>"));return;}ts.invite(target.getUniqueId(),t.id(),p.getUniqueId());p.sendMessage(Text.mm("<green>Invitation sent.</green>"));target.sendMessage(Text.mm("<green>"+t.name()+" invited you. <yellow>/team join "+t.tag()+"</yellow></green>"));}
 private void kick(Player p,String[] a,Team t){if(t==null){msg(p,"not_in_team",Map.of());return;}if(t.member(p.getUniqueId()).role()==TeamRole.MEMBER){msg(p,"not_admin",Map.of());return;}if(a.length<2)return;Player q=Bukkit.getPlayerExact(a[1]);if(q==null||!t.hasMember(q.getUniqueId())){msg(p,"member_not_found",Map.of());return;}if(t.member(q.getUniqueId()).role()==TeamRole.OWNER){msg(p,"member_not_found",Map.of());return;}ts.removeMember(t,q.getUniqueId());p.sendMessage(Text.mm("<green>Member kicked.</green>"));}
 private void promote(Player p,String[] a,Team t){if(t==null||t.member(p.getUniqueId()).role()!=TeamRole.OWNER){msg(p,"not_owner",Map.of());return;}if(a.length<2)return;Player q=Bukkit.getPlayerExact(a[1]);if(q==null||!t.hasMember(q.getUniqueId())){msg(p,"member_not_found",Map.of());return;}TeamMember old=t.member(q.getUniqueId());if(old.role()!=TeamRole.MEMBER)return;t.removeMember(q.getUniqueId());t.addMember(new TeamMember(old.uuid(),old.name(),TeamRole.ADMIN,old.joinedAt(),old.lastSeen(),old.server(),old.points()));ts.save(t);p.sendMessage(Text.mm("<green>Promoted.</green>"));}
 private void transfer(Player p,String[] a,Team t){if(t==null||t.member(p.getUniqueId()).role()!=TeamRole.OWNER){msg(p,"not_owner",Map.of());return;}if(a.length<2)return;Player q=Bukkit.getPlayerExact(a[1]);if(q==null||!t.hasMember(q.getUniqueId())){msg(p,"member_not_found",Map.of());return;}plugin.gui().openConfirm(p,"transfer",q.getName());}
 private void disband(Player p,Team t){if(t==null){msg(p,"not_in_team",Map.of());return;}if(t.member(p.getUniqueId()).role()!=TeamRole.OWNER){msg(p,"not_owner",Map.of());return;}plugin.gui().openConfirm(p,"disband",t.name());}
 private void chatToggle(Player p,Team t){if(t==null){msg(p,"not_in_team",Map.of());return;}ChatListener.toggle(p.getUniqueId());p.sendMessage(Text.mm("<green>Team chat "+(ChatListener.enabled(p.getUniqueId())?"enabled":"disabled")+".</green>"));}
 private void ally(Player p,String[] a,Team t){if(t==null||t.member(p.getUniqueId()).role()==TeamRole.MEMBER){msg(p,"not_admin",Map.of());return;}if(a.length<2)return;Team other=ts.byTag(a[1]);if(other==null){msg(p,"team_not_found",Map.of());return;}p.sendMessage(Text.mm("<green>Alliance request sent to <white>"+other.name()+"</white>.</green>"));}
 @Override public List<String> onTabComplete(CommandSender s,Command c,String a,String[] args){if(args.length==1)return List.of("create","disband","delete","transfer","promote","invite","join","kick","chat","ally","info","browse","top","leaderboard","help").stream().filter(x->x.startsWith(args[0].toLowerCase())).toList();return List.of();}
}
